set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR avr8)

set(CMAKE_C_COMPILER avr-gcc)
set(CMAKE_C_COMPILER_WORKS ON)
set(CMAKE_CXX_COMPILER avr-g++)
set(CMAKE_CXX_COMPILER_WORKS ON)
set(CMAKE_ASM_COMPILER avr-gcc)

set(CMAKE_EXECUTABLE_SUFFIX "")

set(ARCH AVR8)
